//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.Adapters
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.RegistrationAttemptAnswers = new HashSet<RegistrationAttemptAnswer>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid InitiativeId { get; set; }
        public System.Guid ChallengeTypeId { get; set; }
        public string Question { get; set; }
        public Nullable<System.Guid> ChallengeYesNoId { get; set; }
        public Nullable<System.Guid> ChallengeMultipleChoiceId { get; set; }
    
        public virtual ChallengeMultipleChoice ChallengeMultipleChoice { get; set; }
        public virtual ChallengeType ChallengeType { get; set; }
        public virtual ChallengeYesNo ChallengeYesNo { get; set; }
        public virtual Initiative Initiative { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationAttemptAnswer> RegistrationAttemptAnswers { get; set; }
    }
}
