//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.Adapters
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeMultipleChoiceItem
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public System.Guid ChallengeMultipleChoiceId { get; set; }
    
        public virtual ChallengeMultipleChoice ChallengeMultipleChoice { get; set; }
    }
}
