//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.Adapters
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InitiativesEntities : DbContext
    {
        public InitiativesEntities()
            : base("name=InitiativesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChallengeMultipleChoice> ChallengeMultipleChoices { get; set; }
        public virtual DbSet<ChallengeMultipleChoiceItem> ChallengeMultipleChoiceItems { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<ChallengeType> ChallengeTypes { get; set; }
        public virtual DbSet<ChallengeYesNo> ChallengeYesNoes { get; set; }
        public virtual DbSet<Initiative> Initiatives { get; set; }
        public virtual DbSet<RegistrationAttemptAnswer> RegistrationAttemptAnswers { get; set; }
        public virtual DbSet<RegistrationAttempt> RegistrationAttempts { get; set; }
    }
}
