//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.Adapters
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAttemptAnswer
    {
        public System.Guid Id { get; set; }
        public System.Guid ChallengeId { get; set; }
        public System.Guid RegistrationAttemptId { get; set; }
        public Nullable<int> AnswerYesNo { get; set; }
        public string AnswerMultipleChoice { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual RegistrationAttempt RegistrationAttempt { get; set; }
    }
}
